### ISSUE TITLE
XML for adding into toolbox is missing

### ISSUE THREAD

**Issue by anisyusof-sc** [jwill4/Zumo32U4Blocks#6]
Hi,

After building with the 2 new zumo javascripts, I believe that we need to append the xml at the end of index.html and add into toolbox. Can we have the required xml?

Thanks! Looking forward to test it on my zumos.

**Comment by anisyusof-sc** [comment]
Alright, I got it. the <category> tags are not displayed properly in github's README. Just have to add:
`<category name="Zumo">
           <block type="output_leftzmotor"></block>
           <block type="output_rightzmotor"></block>
           <block type="zprox_sense"></block>
           <block type="button_a"></block>
           <block type="button_b"></block>
           <block type="button_c"></block>
           <block type="lcd_clear"></block>
           <block type="lcd_string"></block>
           <block type="lcd_number"></block>
    </category>`

**Comment by jwill4** [comment]
Thank you taipan541.  Sorry for the lack of assistance.  I have now uploaded the index.html file to the repository.  Dont take my slow reply as a lack of interest.  I am very interested in any further comments.

**Comment by anisyusof-sc** [comment]
Its alright, no worries! Thank you for developing this. I appreciate your work and dedication in educating kids with the use of zumo robot. 

On a side note, I have forked your project and include several other I/O like line sensors, LEDs etc. You may find it useful to further extend this project.

**Comment by jwill4** [comment]
New Proximity blocks added.  The previous implementation was not complete.

**Comment by jwill4** [comment]
Ha Haa! You're way ahead of me.  I was about to do the line sensor blocks myself, but then i noticed you're all over it!  I've merged our code manually into my repository, hope you don't mind.  I think the only difference between your fork and my master is the 2 proximity sensor blocks.  Both work, i just kept mine.  Thanks for all your work.  My students will be very grateful.  They were getting a bit sick of just driving around blind.

**Comment by anisyusof-sc** [comment]
I'm glad to hear that! with the line sensors, your students can program the robot to follow a line and even perform maze traversal. Hope your students enjoyed as much as our students do. Keep in touch.

**Comment by jwill4** [comment]
Cheers, im building a mini sumo bot ring at the moment.  

My programming challenge is to start blocklyduino and the webserver in one click, from a flash drive.  

Actually i prefer my students to cut-and-paste the code into the Arduino IDE because then they start to play with the code there (in the IDE) instead of going back to the Blocks.

Case in point: i notice the backwards direction doesn't work on the "Both Motors" block.  I just insert a negative sign in the code in the IDE.   

Not sure why the block doesn't work...looks ok.  I can see how you could re-write it to be more complicated, like the original motor blocks, but it shouldn't be necessary.

**Comment by anisyusof-sc** [comment]
Hi,

thank you for pointing out the bug. I did not thoroughly test these blocks and I missed that out. The negative works, but there is an issue with the corresponding names. I have fixed it by removing the "_L" on both of the conditions. Alternatively, you may view my commit at 6a0cd885d09f1ac1c8e765619d39e7e22f29c55f .

I have built a sumo ring on an old table by using spray paint, as shown in the picture below.
![sumo ring](https://cloud.githubusercontent.com/assets/10651752/16401042/89a1d38c-3d13-11e6-8e2f-e436315fb598.png)
I followed the standard specification for mini robot class, which is 77cm total diameter including 2.5cm white border thickness. This is the standard specification that is used in mini sumo robot competition. There are various sizes for the sumo ring for the respective robot classes.

As for your one-click solution, you may want to consider writing a python script to create an executable python file that opens a web browser and run the server. Let me know if you need assistance.

**Comment by jwill4** [comment]
taipan541
Thanks for bothmotor fix. i have updated my repository 

Nice sumo bot ring.  Long way to fall though.

One-click solution so far:
I'm not sure how to do shell commands in python.  So i've used "batch" files.

On my iMac i've created the following .command file and made it executable.

```
#! /bin/bash
cd /Users/All/Documents/Jason/Coding/Arduino/Blocklyduino-1.4
open blockly/apps/blocklyduino/index_v1_4.html
python arduino_web_server.py --port=/dev/cu.usbmodemFD131
```

On the school PCs i will use a .bat file to do the same.  I haven't tried it but i anticipate it will be straight forward.

It works ok but only if the Zumobot is allocated to the same port every time, which it isn't.
